server:
  port: 8443
#  ssl:
#    key-store: classpath:keystore.jks
#    key-store-password: kurento
#    key-store-type: JKS
#    key-alias: kurento-selfsigned

spring:
  banner:
    location: classpath:banner.txt

